apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-pod
  labels:
    app: web
spec:
  replicas: 2
  selector: 
   matchLabels:
     app: web
  template:
    metadata:  
     labels:
      app: web
    spec: 
      containers:
        - name: c1
          image: nginx
          ports:
           - containerPort: 80

